---
title: "Tema 3. Primera parte - Índices de diversidad"
format:
  html:
    toc: true
    toc-depth: 4
    toc-location: left
    toc_float: true
    css: estilos.css
engine: knitr
filters:
  - webr
---

### Breve introducción

Los métodos de ordenación se emplean habitualmente para representar datos que tienen muchas dimensiones (como por ejemmplo los datos de composición específica) a lo largo de un número reducido de ejes.Las bases de datos con multitud de variables son difíciles de representar. En las ordenaciones se asume que la información que contiene nuestra base de datos multivariante tiene información redundante. Así, el análisis de ordenación simplifica o "reduce" esa información para que podamos visualizar las muestras. Esta visualización ofrece una forma sencilla de analizar cómo se ordenan las muestras y ver cuáles son más parecidas entre sí.

Además, una vez que tenemos las muestras "ordenadas" es frecuente que queramos saber si ese orden se corresponde con algún grupo en particular (por ejemplo, el hábitat en el que recogimos las muestras) o con variables ambientales (por ejemplo, si las muestras se ordenan a lo largo de un gradiente de humedad). Algunos métodos de ordenación permiten hacer este tipo de análsis.

En este tema vamos centrarnos en análisis de componentes principales que es muy útil para comunidades de especies en las que las diferencias entre comunidades no son muy grandes y, por lo tanto, no hay muchas especies que están ausentes de buena parte de las localidades (la base de datos tiene pocos ceros).

Cuando la composición específica es muy heterogénea o tenemos otro tipo de datos lo mejor es optar por otro tipo de análisis de ordenación. Una buena muy página en la que podéis explorar todas las posibilidades que ofrecen este tipo de análisis es la publicada por David Zeleny [vínculo aquí](https://www.davidzeleny.net/anadat-r/doku.php/en:ordination)

Como siempre vamos a trabajar con la base de datos de herbáceas de Alberta.

```{webr-r}
comm_alberta <- read.csv("https://raw.githubusercontent.com/ngmedina/UAMBioDivR/main/Alberta%20grassland/grassland.community.csv")
```

Existen varias funciones que permiten hacer PCAs en R. Por ejemplo, la función `rda()` en el paquete vegan, la función `prcomp` en el paquete stats y la función `pca` en el paquete labdsv.

Vamos a utilizar la función `rda` del paquete vegan.

Comenzamos por cargar las librerías

```{webr-r}
library(vegan)
```

La función `rda` permite hacer Principal component Analysis (PCA), redundancy analysis (RDA),

```{webr-r}
pca_alb_com <- rda(comm_alberta[, -1], method ="pa", scale =F)

```

```{webr-r}
pca_alb_com
```

Para acceder a los elementos de resultados podemo utilizar el comando `summary`

```{webr-r}
sum <- summary(pca_alb_com)
```

El resumen del análisis nos muestra la proporción de la varianza explicada por cada eje. Esto lo podemos interpretar como la cantidad de información que contienen nuestros ejes con respecto a la información que contiene la base de datos.

#### [Ejercicio 1. En el ejemplo de Alberta ¿Qué porcentaje de variabilidad absorbe el primer eje?]{style="color: blue;"} {.unnumbered}

#### [Ejercicio 2. En el ejemplo de Alberta ¿Cuál es la especie que tiene mayor peso en el eje 1?]{style="color: blue;"} {.unnumbered}

#### [Ejercicio 3. En el ejemplo de Alberta ¿Cuál es la especie que tiene mayor peso en el eje 2?]{style="color: blue;"} {.unnumbered}

#### [Ejercicio resuelto. ¿Qué peso tiene las especies *Artemisia cana* y *Artemisia rigida* en el eje 1?]{style="color: blue;"} {.unnumbered}

```{webr-r}
rows <- rownames(sum$species) %in% c("Artemisia_cana", "Artemisia_frigida")
sum$species[rows,]
```

Ahora pasamos a representar los datos

También podemos hacer una representación gráfica del peso de la varianza que recoje cada eje

```{webr-r}
plot(pca_alb_com)
```

Como podéis ver los nombres de las especies no se leen porque ocupan demasiado espacio. Una posibilidad para solucionarlo es abreviar los nombres de las especies. Para eso, por convención se cogen las cuatro letras del epiteto genérico y las cuatro primeras letras del epiteto de especie o subespecie.

¡OJO! En la base de datos las especies están separadas por un guión bajo. Lo primero que tenemos que hacer es sustituir el guión bajo por un espacio para lo que usaremos la función `gsub`

```{webr-r}
sp <- colnames(comm_alberta)
sp <- gsub(pattern =  "_", replacement = " ", sp, fixed = TRUE)
```

```{webr-r}
sp_abrev <- make.cepnames(sp)
```

Cambiamos el nombre de las columnas de la matriz.

```{webr-r}
colnames(comm_alberta) <- sp_abrev
```

Y recalculamos

```{webr-r}
pca_alb_com <- rda(comm_alberta[, -1], method ="pa", scale =F)
ordiplot(pca_alb_com, type = "text")
```

NOTA: En análisis de componentes principales (PCA) también se puede emplear para resumir información ambiental. Es adecuado cuando tenemos muchas variables ambientales y queremos simplificar (reducir las dimensiones). Por ejemplo, lo podríamos emplear para resumir la información climática de la base de datos de AFLIBER.

```{webr-r}
env_afliber <- read.csv("https://raw.githubusercontent.com/ngmedina/UAMBioDivR/main/Cistus%20database/afiber_clim_sel.csv")
```

```{webr-r}
colnames(env_afliber) <- 
pca_afl_com <- rda(env_afliber[,-c(1:4)], method ="pa", scale =T)
plot(pca_afl_com)
```

```{webr-r}
summary(pca_afl_com)
```
