---
title: "Tema 3. Primera parte - Índices de diversidad"
format:
  html:
    toc: true
    toc-depth: 4
    toc-location: left
    toc_float: true
    css: estilos.css
engine: knitr
filters:
  - webr
---

# Datos de composición específica

En la próxima sesión vamos a explorar índices de biodiversidad. Para ello vamos a emplear bases de datos de la abundancia de especies en herbazales de Alberta en Canada con el que ya estáis familiarizados. La base de datos original podéis descargarla [aquí](https://kembellab.ca/r-workshop/)

Recordad que los los datos provienen de un estudio de plantas que se realizó en parcelas de 20 x 20 m. Los datos de abundancia corresponden la cobertura de cada especie en proporción al total de la parcela.

## Cargar datos

Vamos a cargar los datos directamente de una página web. En R esto es muy sencillo si los datos tienen el formato adecuado. De hecho, vamos a emplear el mismo código que empleamos cuando cargamos datos desde un archivo guardado en nuestro ordenador.

Para ver el formato en el que los datos están almacenados en la nube pinchad [aquí](https://raw.githubusercontent.com/ngmedina/Rbiodiversidad/data/grassland.community.csv?token=GHSAT0AAAAAABW67JU2B2REWKV4YDPKDVTUYW62OKA)

Cargamos los datos:

```{webr-r}
comm_alberta <- read.csv("https://raw.githubusercontent.com/ngmedina/UAMBioDivR/main/Alberta%20grassland/grassland.community.csv")
```

y echamos un vistazo a las primeras filas para comprobar que los datos se han cargado correctamente

```{webr-r}
head(comm_alberta)
```

# Análisis exploratorio de datos

Lo primero que hacemos cuando nos enfrentamos a una base de datos nueva es hacer un primer análisis exploratorio que consiste en hacer

1.  Resumen de datos

2.  Representación de los datos

## Resumen de datos

```{webr-r}
summary(comm_alberta)
```

Comprobamos las dimensiones de nuestra matriz que nos dicen el número de parcelas (primer número, filas) y el número de especies (segundo número, columnas)

```{webr-r}
dim(comm_alberta)
```

## Representación de datos

Además, es buena idea representar histogramas de distribución de datos. Por ejemplo de las especies. Esta gráfica nos muestra que en la mayor parte de las cuadrículas *Antennaria parviflora* tiene un cobertura entre 0 y 10 % pero que en alguna de las cuadrículas puede llegar a ocupar el 70%

```{webr-r}
hist(comm_alberta$Antennaria_parvifolia)
```

## Otras operaciones para explorar los datos

Podemos ver qué especie es la más abundante. Para ello tenemos que sumar los valores de cada columna. Podríamos hacerlo columna a columna. Por ejemplo, para la especie de la segunda columna que es *Antennaria parviflora*

```{webr-r}
colnames(comm_alberta)[2]
sum(comm_alberta[,2])
```

Si tenemos 100 especies esto implicaría repetir el código de arriba 100 veces. Sin embargo, existe una forma rápida y sintética de hacer esto mismo utilizando la función ColSums.

```{webr-r}
colsums <- colSums(comm_alberta[,-1])
```

Además podemos ver cuál de las parcelas tiene la mayor cobertura

```{webr-r}
rowsums <- rowSums(comm_alberta[,-1])
```

# Índices de diversidad taxonómica

Hay muchas maneras de analizar la diversidad taxonómica. La más sencilla es contar el número de especies de cada unidad geográfica (en nuestro ejemplo parcelas). De hecho hay muchísimos índices de diversidad y bastante controversia con respecto a cuáles deberían usarse.

Si os interesa el tema tenéis algunos enlaces a páginas web y artículos interesantes sobre índices de biodiversidad aquí abajo:

<https://archetypalecology.wordpress.com/2018/02/20/biodiversity-indices-concepts-and-r-implementations-in-progress/>

<https://www.nature.com/articles/35012221>

<https://onlinelibrary.wiley.com/doi/10.1111/oik.07202>

#### Ejercicio 1 Busca en internet paquetes de R que permitan calcular índices de diversidad taxonómica

Nosotros vamos a utilizar la librería *vegan* para estimar diferentes índices de diversidad

```{webr-r}
library(vegan)
```

En el código que sigue a continuación tenéis ejemplos que muestran como estimar índices de diversidad utilizando los datos de comunidad de las herbáceas de Alberta.

Primero calculamos la riqueza de especies por cada cuadrícula

```{webr-r}
## Riqueza de especies
S <- specnumber(comm_alberta[,-1]) ## rowSums(comm_alberta > 0) hace lo mismo...
```

Pregúnta. ¿Por qué utilizo el código comm_alberta\[,-1\]?{style="color: blue;"}

Y la riqueza total

```{webr-r}
## Riqueza total
Stot <- dim(comm_alberta[-1])
```

Ahora calculamos otros índices de diversidad, el índice de Shannon es uno de los más frecuentes. Para ello utilizaremos la función diversity

Pregunta: ¿Recuerdas lo que era una función en R?{style="color: blue;"}

```{webr-r}
H <- diversity(comm_alberta[,-1], "shannon")
```

Pero la función nos permite calcular muchos más.

```{webr-r}
# Simpson
simp <- diversity(comm_alberta[,-1], "simpson")
# Inv simp
invsimp <- diversity(comm_alberta[,-1], "inv")

```

# Diversidad funcional

Sin embargo, la diversidad taxonómica no es el único aspecto de la biodiversidad. Además, también podemos cuantificar la diversidad de rasgos funcionales. De hecho, cada vez es más habitual reconocer la imporancia de este aspecto.

Para estimar la diversidad funcional vamos a emplear una base de datos de rasgos funcionales para las especies que están presentes en las cuadrículas de los datos de Alberta.

Cargar la base de datos de rasgos

```{webr-r}
traits <- read.csv("https://raw.githubusercontent.com/ngmedina/UAMBioDivR/main/Alberta%20grassland/species.traits.csv")
```

Los rasgos que han medido en este estudio incluyen SLA, Area de las hojas, Grosor de las hojas, venación, densidad del tejido y longitud de las raíces, etc.

Hay multitud de opciones pero para el ejemplo vamos a emplear el paquete FD

```{webr-r}
library(FD)
help(FD)
```

```{webr-r}
fd <- dbFD(traits, comm_alberta[,-1])
```

[**¿Qué nos dice el error?**]{style="color: blue;"}

Conseguir que las bases de datos estén harmonizadas y en el formato que necesitamos para las diferentes funciones es una de las tareas que más tiempo nos va a llevar cuando estamos haciendo un análisis. Tenéis que asumir desde un principio que siempre va a ser así.

En este caso tenemos que ordenar las especies en la comunidad exactamente igual en las dos matrices.

Primero ordenamos la base de datos de las abundancias de las especies para que las columnas estén el mismo orden que en la base de datos de rasgos

```{webr-r}

order <- match(traits$species, colnames(comm_alberta[,-1]))

comm_alberta_ordered <- comm_alberta[,-1][,order]
```

Después comprobamos si el orden de las especies en la tabla de rasgos es alfabético

```{webr-r}
traits$species == colnames(comm_alberta_ordered)
```

¿Ahora funciona?

```{webr-r}
fd <- dbFD(traits, comm_alberta_ordered)
```

[**¿Por qué sigue dando el mismo error?**]{style="color: blue;"}

Los errores de R no siempre son intuitivos, por eso siempre que os enfrentéis a una función nueva conviene explorar la ayuda y ver los ejemplos de la función para ver si podéis encontrar el error. Vamos a ello

```{webr-r}
?dbFD
```

Veamos el ejemplo 1 de la ayuda

```{webr-r}
ex1 <- dbFD(dummy$trait, dummy$abun)
```

Vamos a explorar qué datos emplean

#### Ejercicio 2: ¿Qué tipo de objeto es dummy?

```{webr-r}
# Escribe aquí tu respuesta
```

<button onclick="let x=document.getElementById(&#39;sol1&#39;); x.style.display = (x.style.display===&#39;none&#39;) ? &#39;block&#39;:&#39;none&#39;;" style="background-color:#407FD0; color:white; border:none; padding:6px 12px; border-radius:5px; cursor:pointer;">

Mostrar/Ocultar solución

</button>

::: {#sol1 style="display:none; margin-top:10px; border:1px solid #ccc; padding:10px; border-radius:5px;"}
Solución:\

```{webr-r}
class(dummy$trait)
class(dummy$abun)
```
:::

#### Ejercicio 3: ¿Qué estructura tiene el objeto dummy?

```{webr-r}
# Escribe aquí tu respuesta
```

<button onclick="let x=document.getElementById(&#39;sol2&#39;); x.style.display = (x.style.display===&#39;none&#39;) ? &#39;block&#39;:&#39;none&#39;;" style="background-color:#407FD0; color:white; border:none; padding:6px 12px; border-radius:5px; cursor:pointer;">

Mostrar/Ocultar solución

</button>

::: {#sol2 style="display:none; margin-top:10px; border:1px solid #ccc; padding:10px; border-radius:5px;"}
Solución:\

```{webr-r}
str(dummy)
```
:::

Como véis el objeto tiene dos tablas. Los objetos de la lista tienen nombres, uno es una "data.frame" en la que están los rasgos (trait) y y el otro contiene la abundancia (abun) de las especies.

Ahora comparemos esa tabla con la de los rasgos del ejemplo con la de las comunidades de Alberta

```{webr-r}
head(traits)
head(dummy$trait)
```

[**Pregunta: ¿Notas alguna diferencia?**]{style="color: blue;"}

```{webr-r}
# Escribe aquí tu respuesta
```

<button onclick="let x=document.getElementById(&#39;sol3&#39;); x.style.display = (x.style.display===&#39;none&#39;) ? &#39;block&#39;:&#39;none&#39;;" style="background-color:#407FD0; color:white; border:none; padding:6px 12px; border-radius:5px; cursor:pointer;">

Mostrar/Ocultar solución

</button>

::: {#sol3 style="display:none; margin-top:10px; border:1px solid #ccc; padding:10px; border-radius:5px;"}
Solución:\

```{webr-r}
# Los nombres de las especies están como **nombres de filas** en "dummy" mientras que en la tabla traits aparece como columna
```
:::

Las especies en la tabla del ejemplo ("dummy") están como nombres de fila, no como una columna separada. Para adaptar el formato de nuestra tabla tenemos que asignar los nombres de las filas y eliminar la columna sp

```{webr-r}
rownames(traits) <- traits$species
traits <- traits[,-1]
```

Ahora ya podemos calcular el índice de diversidad funcional

```{webr-r}
fd <- dbFD(traits, comm_alberta_ordered)
```

# Diversidad filogenética

Del mismo modo que hay varias formas de calcular la diversidad funcional también hay varias maneras de calcular la diversidad filogenética. Nosotros nos vamos a centrar tan solo en una de ellas, la diversidad filogenética de Faith.

La diversidad filogenética de Faith (PD) es una medida de biodiversidad que resulta de sumar la longitud de todas las ramas de las especies en un árbol filogenético.

Vamos a cargar el árbol filogenético de los datos de Alberta. Los análisis los haremos con la librería picante

```{webr-r}
library(picante)
```

```{webr-r}
tree_alberta <- read.tree("https://raw.githubusercontent.com/ngmedina/UAMBioDivR/main/Alberta%20grassland/grassland.phylogeny.newick")
```

```{webr-r}
pd <- picante::pd(comm_alberta_ordered, tree_alberta)
```

Hagamos un primer análisis exploratorio de la relación entre la riqueza, la diversidad filogenética y la funcional

```{webr-r}
# Combinar todo en un solo dataframe
datos_combinados <- S %>%
  bind_cols(
    Fric = fd$FRic,
    FEve = fd$FEve,
    FDiv = fd$FDiv,
    FDis = fd$FDis,
    PD = pd$PD
  )

# comparar entre índices
pairs(datos_combinados, pch = "+", col = "blue")


```
